/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct str {
	char *s;
};
typedef struct str str;

struct strw {
	char *file;
	char *s;
};
typedef struct strw strw;

#define APP_PROG 0x4562877
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define files 1
extern  str * files_1(void *, CLIENT *);
extern  str * files_1_svc(void *, struct svc_req *);
#define readFile 2
extern  str * readfile_1(str *, CLIENT *);
extern  str * readfile_1_svc(str *, struct svc_req *);
#define writeFile 3
extern  int * writefile_1(strw *, CLIENT *);
extern  int * writefile_1_svc(strw *, struct svc_req *);
#define usuarioValido 4
extern  int * usuariovalido_1(str *, CLIENT *);
extern  int * usuariovalido_1_svc(str *, struct svc_req *);
extern int app_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define files 1
extern  str * files_1();
extern  str * files_1_svc();
#define readFile 2
extern  str * readfile_1();
extern  str * readfile_1_svc();
#define writeFile 3
extern  int * writefile_1();
extern  int * writefile_1_svc();
#define usuarioValido 4
extern  int * usuariovalido_1();
extern  int * usuariovalido_1_svc();
extern int app_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_strw (XDR *, strw*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_strw ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
