/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "app.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->s, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_strw (XDR *xdrs, strw *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file, 1024))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->s, 1024))
		 return FALSE;
	return TRUE;
}
