/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"


void
app_prog_1(char *host)
{
	CLIENT *clnt;
	str  *result_1;
	char *files_1_arg;
	str  *result_2;
	str  readfile_1_arg;
	int  *result_3;
	strw  writefile_1_arg;
	int  *result_4;
	str  usuariovalido_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, APP_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = files_1((void*)&files_1_arg, clnt);
	if (result_1 == (str *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = readfile_1(&readfile_1_arg, clnt);
	if (result_2 == (str *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = writefile_1(&writefile_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = usuariovalido_1(&usuariovalido_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	app_prog_1 (host);
exit (0);
}
