/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

str *
files_1_svc(void *argp, struct svc_req *rqstp)
{
	static str  result;

	/*
	 * insert server code here
	 */

	return &result;
}

str *
readfile_1_svc(str *argp, struct svc_req *rqstp)
{
	static str  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
writefile_1_svc(strw *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
usuariovalido_1_svc(str *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
