/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <dirent.h>

#include "app.h"

str *files_1_svc(void *argp, struct svc_req *rqstp){
	static str  result;

	/*
	 * insert server code here
	 */
	DIR *directorio;
    struct dirent *entrada;
    size_t espacioDisponible = 1024;

    result.s = (char *)malloc(1024);
    if (result.s == NULL) {
        perror("malloc failed");
        exit(EXIT_FAILURE);
    }
    result.s[0] = '\0';

    directorio = opendir("./");
    if (directorio == NULL) {
        perror("No se puede abrir el directorio");
        return &result;
    }

    while ((entrada = readdir(directorio)) != NULL) {
        if (entrada->d_name[0] != '.') {
            size_t nombreArchivoLongitud = strlen(entrada->d_name);

            if (nombreArchivoLongitud + 1 < espacioDisponible) {
                strcat(result.s, entrada->d_name);
                strcat(result.s, "\n");

                espacioDisponible -= (nombreArchivoLongitud + 1);
            }
        }
    }

    closedir(directorio);
	
	return &result;
}

str *readfile_1_svc(str *argp, struct svc_req *rqstp){
	static str  result;

	/*
	 * insert server code here
	 */
	FILE *archivo;
    char *buffer = malloc(1024 * sizeof(char));
	result.s = malloc(1024 * sizeof(char));
	result.s[0] = '\0';

    archivo = fopen(argp->s, "r");
    if (archivo == NULL) {
        perror("Error al abrir el archivo");
        return &result;
    }

    while (fgets(buffer, 1024, archivo) != NULL) {
        strcat(result.s, buffer);
    }
	
	size_t len = strlen(result.s);
	if (len > 0 && result.s[len - 1] == '\n') {
		result.s[len - 1] = '\0';
	}

    fclose(archivo);
	free(buffer);

	return &result;
}

int *writefile_1_svc(strw *argp, struct svc_req *rqstp){
	static int  result;

	/*
	 * insert server code here
	 */
    FILE *archivo = fopen(argp->file, "w");

    if (archivo == NULL) {
        printf("No se pudo abrir el archivo %s\n", argp->file);
        result = 0;
    }else{
		
		size_t longitud = strlen(argp->s);
		fwrite(argp->s, sizeof(char), longitud, archivo);

		fclose(archivo);

		printf("Se ha escrito correctamente en el archivo %s\n", argp->file);
		result = 1;
	}
	return &result;
}

int *usuariovalido_1_svc(str *argp, struct svc_req *rqstp){
	static int  result = 0;
	
	/*
	 * insert server code here
	 */
	FILE *file = fopen("./users.txt", "r");
    if (!file) {
        perror("No se puede abrir el archivo");
    }else{
		result = 0;
		char *token = argp->s;
		printf("Buscando si existe el token '%s'\n", token);
		char line[1024 + 2];
		while (fgets(line, sizeof(line), file)) {
			line[strcspn(line, "\n")] = 0;

			// Separar por ';'
			char *user = strtok(line, ";");
			char *pw = strtok(NULL, ";");
			char *file_token = strtok(NULL, ";");

			if (file_token && strcmp(file_token, token) == 0) {
				result = 1; // Token encontrado
			}
		}
		
		if(result)
			printf("Token '%s' encontrado.\n", token);
		else
			printf("No se encontró el token '%s'.\n", token);
		
		fclose(file);
	}

	return &result;
}
